### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by maxgerhardt** [arduino/go-timeutils#1]
For PlatformIO (Python-based) I'd like to emulate exactly all functions here in python so that the build process has the same result as in the Arduino IDE.

I.e. getting the result of https://github.com/arduino/arduino-cli/blob/63f1e1855aa4c91415480be40fc49fd50d597e35/legacy/builder/setup_build_properties.go#L121-L125

Since Go is a compiled language I'd rather not compile this function for every supported target and have it in portable Python. Even better if it has no dependencies on external libraries.

Is the following code sufficient? 
```py
import time
time_utc = int(time.time())
# extra.time.zone
time_zone = -time.timezone
is_dst = time.daylight and time.localtime().tm_isdst > 0
# extra.time.dst
time_dst = - (time.altzone if is_dst else 0)
```

At the time of writing, the produced values matcho those that I see in the Arduino IDE at least.
```
-Wl,--defsym=__RTC_EPOCH__=1672157983
-Wl,--defsym=__RTC_ZONE__=3600
-Wl,--defsym=__RTC_DST__=0 
```
(reference:)
```
-Wl,--defsym=__RTC_EPOCH__={extra.time.utc}
-Wl,--defsym=__RTC_ZONE__={extra.time.zone}
-Wl,--defsym=__RTC_DST__={extra.time.dst}
```

**Comment by cmaglie** [comment]
LGTM
